version: "3.9"

services:
  api:
    build:
      context: .
    container_name: dotnet-api
    ports:
      - "7021:7021"
    environment:
      ASPNETCORE_URLS: https://0.0.0.0:7021
      ASPNETCORE_ENVIRONMENT: "Development" 
      ScanUploadProxy__KeycloakClientId: "${SCANUPLOADPROXY_APIKEY}" 
      ScanUploadProxy__KeycloakClientSecret: "${SCANUPLOADPROXY_ENDPOINT}"
    networks:
      - appnet

  client:
    build:
      context: ./client-app
    container_name: react-client
    ports:
      - "3002:3002"
    networks:
      - appnet
    depends_on:
      - api

networks:
  appnet:
    driver: bridge
