services:
  scanupload.dotnet.example:
    build:
      context: .
    container_name: scanupload-dotnet-example
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: "Qa" 
      ScanUploadProxy__KeycloakClientId: "${ScanUploadProxy__KeycloakClientId}" 
      ScanUploadProxy__KeycloakClientSecret: "${ScanUploadProxy__KeycloakClientSecret}"
    networks:
      - appnet

  scanupload.react.example.client:
    build:
      context: ./client-app
    container_name: scanupload-react-example-client
    ports:
      - "3002:3002"
    environment:
      DOCKER: "true"
    networks:
      - appnet
    depends_on:
      - scanupload.dotnet.example

networks:
  appnet:
    driver: bridge
