@ScanUpload.Example.DotnetApi_HostAddress = https://localhost:7021

###
POST {{ScanUpload.Example.DotnetApi_HostAddress}}/scanupload-api/session
Accept:application/json
Content-Type: application/json 

{ 

}